{"name":"DemoDataflow","description":"","version":"1.0","culture":"en-US","modifiedTime":"2022-05-20T05:07:26.6181886+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"DemoDataflow":{"queryId":"dd3c5ec5-d38b-43ab-a7a4-4828dea66864","queryName":"DemoDataflow","loadEnabled":true}},"document":"section Section1;\r\nshared DemoDataflow = let\r\n  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45W8k7MLE4tUtJRck7MyUzLL8rLTFSK1YlWcs7PK8kvzgdKhCcWZ2TmpZfk5ynFxgIA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Customer = _t, Location = _t])\r\nin\r\n  Source;\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"DemoDataflow","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"DemoDataflow.csv"},"attributes":[{"name":"Customer","dataType":"string"},{"name":"Location","dataType":"string"}]}]}